### ISSUE TITLE
Testing Issues

### ISSUE THREAD

**Issue by ShanaLMoore** [learn-co-curriculum/angular-hello-world-lab#12]
Hi again! Having issues running this test. I did the update to learn test but still received the following error: 

Shana: angular-hello-world-lab-v-000
♥ learn
Installing missing dependency karma...
npm ERR! tar.unpack untar error /Users/Shana/.npm/karma-cli/0.1.2/package.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "karma-cli"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path /usr/local/lib/node_modules/karma-cli
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/karma-cli'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/karma-cli']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/karma-cli',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/karma-cli',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Shana/Development/code/angular-hello-world-lab-v-000/npm-debug.log
/Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/open3.rb:193:in `spawn': No such file or directory - karma (Errno::ENOENT)
    from /Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/open3.rb:193:in`popen_run'
    from /Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/open3.rb:93:in `popen3'
    from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/learn-test-2.1.1/lib/learn_test/strategies/karma.rb:56:in`run_karma'
    from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/learn-test-2.1.1/lib/learn_test/strategies/karma.rb:18:in `run'
    from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/learn-test-2.1.1/lib/learn_test/runner.rb:15:in`run'
    from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/learn-test-2.1.1/bin/learn-test:56:in `<top (required)>'
    from /Users/Shana/.rbenv/versions/2.2.2/bin/learn-test:23:in`load'
    from /Users/Shana/.rbenv/versions/2.2.2/bin/learn-test:23:in `<main>'

**Comment by ShanaLMoore** [comment]
I got help from Sara. I had to run sudo npm install -g karma-cli
